### ISSUE TITLE
NotImplementedError Error thrown during migration

### ISSUE THREAD

**Issue by mustafaozhan** [lupuuss/Mokkery#10]
Hello,

Thank you for this amazing mocking library, thanks to it I get rid of ksp and decreased my build times, also finally I was able to move my project to Kotlin 2.0.

During the migration from Mockative to Mokkery I had various issues and couldn't fix 3 of them. This issue is targeting to one of it.

If you check the linked PR, I have added 3 test classes back(These test classes were working fine with Mockative), I had to remove these classes during Mokkery migration since it was giving the below error:
```
e: Compilation failed: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterPublicSymbolImpl is not supported yet

 * Source files: 
 * Compiler version: 2.0.0
 * Output kind: PROGRAM

e: kotlin.NotImplementedError: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterPublicSymbolImpl is not supported yet
	at org.jetbrains.kotlin.backend.common.linkage.partial.MissingDeclarationStubGenerator.getDeclaration(MissingDeclarationStubGenerator.kt:62)
	at org.jetbrains.kotlin.backend.common.linkage.partial.ClassifierExplorer.exploreSymbol(ClassifierExplorer.kt:96)
	at org.jetbrains.kotlin.backend.common.linkage.partial.ClassifierExplorer.exploreType(ClassifierExplorer.kt:75)
	at org.jetbrains.kotlin.backend.common.linkage.partial.ClassifierExplorer.exploreType(ClassifierExplorer.kt:65)
	at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher.explore(PartiallyLinkedIrTreePatcher.kt:946)
	at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher.toPartiallyLinkedMarkerTypeOrNull(PartiallyLinkedIrTreePatcher.kt:949)
	at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher.access$toPartiallyLinkedMarkerTypeOrNull(PartiallyLinkedIrTreePatcher.kt:43)
	at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$DeclarationTransformer.rewriteTypesInFunction(PartiallyLinkedIrTreePatcher.kt:387)
	at org.jetbrains.kotlin.backend.common.linkage.partial.PartiallyLinkedIrTreePatcher$DeclarationTransformer.visitSimpleFunction(PartiallyLinkedIrTreePatcher.kt:265)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:19)
```

You can see the full log in the link I shared below.

Let me know if anything is needed from my end!

Log: https://github.com/Oztechan/CCC/actions/runs/9615001222/job/26521152675?pr=3583
PR: https://github.com/Oztechan/CCC/pull/3583

**Comment by lupuuss** [comment]
Hi! This error is probably associated with mock class generation. Could you check which type is causing the error?

**Comment by lupuuss** [comment]
Ok. I was able to reproduce the error on my own. I can confirm this is a bug and I'm working on a fix. Thank you for reporting the issue!

**Comment by lupuuss** [comment]
The issue is fixed! I should be able to release it in a few days.

**Comment by mustafaozhan** [comment]
Thank you @lupuuss I confirm that the newly released version fixed the issue.
